# Generated by Django 5.0.4 on 2024-05-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuestionList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_1', models.TextField(blank=True, null=True)),
                ('response_2', models.TextField(blank=True, null=True)),
                ('response_3', models.TextField(blank=True, null=True)),
                ('response_4', models.TextField(blank=True, null=True)),
                ('response_5', models.TextField(blank=True, null=True)),
                ('response_6', models.TextField(blank=True, null=True)),
                ('response_7', models.TextField(blank=True, null=True)),
                ('response_8', models.TextField(blank=True, null=True)),
                ('response_9', models.TextField(blank=True, null=True)),
                ('response_10', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionList.questionlists')),
            ],
        ),
    ]
